# Generated by Django 2.1.2 on 2018-10-31 09:45

import autoslug.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20181031_1145'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('condition', models.CharField(choices=[('', 'Condition'), ('new', 'New'), ('used', 'Used')], max_length=10)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('facebook', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(blank=True, default='ads/default.jpg', upload_to='images/ads/images/ads/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='images/ads/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='images/ads/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='images/ads/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='images/ads/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='images/ads/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='images/ads/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
